<!DOCTYPE html>
<html>

<head>
    <title>MovieHunter</title>
    <link rel="stylesheet" href="./styles/style.css">
</head>

<body>
    <?php require_once "Header.phtml" ?>
    <main>
        <h1>Lista de directores: </h1>
        <section>
            <form action="eliminardirector" method="POST">
                <div class="movies">
                    <?php foreach ($directors as $director) : ?>
                        <a href="director?id=<?php echo $director->{'director_id'}; ?>">
                            <div class="movie">
                                <h3><?php echo $director->{'Nombre'} ?></h3>
                                <h3><?php echo $director->{'Apellido'} ?></h3>
                                <?php if (AuthHelper::isAuthenticated()) : ?>
                                    <input type="hidden" name="id" value="<?php echo $director->director_id; ?>">
                                    <button type="submit" name="eliminar">Eliminar</button>
                                <?php endif; ?>
                            </div>
                        </a>
                    <?php endforeach; ?>
                </div>
            </form>
        </section>
    </main>
    <?php if (AuthHelper::isAuthenticated()) : ?>
        <?php require_once "AddDirectorTemplate.phtml"; ?>
    <?php endif; ?>
    <?php require_once "Footer.phtml" ?>
</body>

</html>