<!DOCTYPE html>
<html>

<head>
    <title>MovieHunter</title>
    <link rel="stylesheet" href="./styles/style.css">
</head>

<body>
    <?php require_once "Header.phtml" ?>
    <main>
        <h1>Lista de directores: </h1>
        <section class="movies">
            <form action="eliminardirector" method="POST">
                <?php foreach ($directors as $director) : ?>
                    <div class="movie">
                        <img src="director1.jpg" alt="Foto Director">
                        <h3><?php echo $director->{'Nombre'} ?></h3>
                        <h3><?php echo $director->{'Apellido'} ?></h3>
                        <?php if (AuthHelper::isAuthenticated()) : ?>
                            <input type="hidden" name="id" value="<?php echo $director->director_id; ?>">
                            <button type="submit" name="eliminar">Eliminar</button>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
            </form>
        </section>
    </main>
    <?php if (AuthHelper::isAuthenticated()) : ?>
        <?php require_once "AddDirectorTemplate.phtml"; ?>
    <?php endif; ?>
    <?php require_once "Footer.phtml" ?>
</body>

</html>