<!DOCTYPE html>
<html>
<head>
    <title>Resumen del Director</title>
</head>
<body>
    
    <?php if (isset($movies) && !empty($movies)): ?>
        <ul>
        <h1>$director</h1>
            <?php foreach ($movies as $movie): ?>
                <li>
                    <?php if (isset($movie->nombre)): ?>
                        <strong>Título:</strong> <?php echo $movie->nombre; ?><br>
                    <?php endif; ?>
                    <?php if (isset($movie->{'fecha de lanzamiento'})): ?>
                        <strong>Año:</strong> <?php echo $movie->{'fecha de lanzamiento'}; ?><br>
                    <?php endif; ?>
                    <?php if (isset($movie->director)): ?>
                        <strong>Director:</strong> <?php echo $movie->director; ?><br>
                    <?php endif; ?>
                    <?php if (isset($movie->genero)): ?>
                        <strong>Género:</strong> <?php echo $movie->genero; ?><br>
                    <?php endif; ?>
                    <?php if (isset($movie->premios)): ?>
                        <strong>Premios:</strong> <?php echo $movie->premios; ?><br>
                    <?php endif; ?>
                    <?php if (isset($movie->{'duracion en min'})): ?>
                        <strong>Duración (min):</strong> <?php echo $movie->{'duracion en min'}; ?><br>
                    <?php endif; ?>
                    <?php if (isset($movie->{'clasificacion por edades'})): ?>
                        <strong>Clasificación por Edades:</strong> <?php echo $movie->{'clasificacion por edades'}; ?><br>
                    <?php endif; ?>
                    <?php if (isset($movie->presupuesto)): ?>
                        <strong>Presupuesto:</strong> <?php echo $movie->presupuesto; ?><br>
                    <?php endif; ?>
                    <?php if (isset($movie->{'estudio de produccion'})): ?>
                        <strong>Estudio de Producción:</strong> <?php echo $movie->{'estudio de produccion'}; ?><br>
                        <br>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php else: ?>
        <p>No se encontraron películas que coincidan con la búsqueda.</p>
    <?php endif; ?>
</body>
</html>