<!DOCTYPE html>
<html>

<head>
    <title>Resumen del Director</title>
</head>

<body>
    <h1>Resultados de la búsqueda de directores</h1>
    <?php if (isset($directors) && !empty($directors)) : ?>
        <ul>
            <h1>Directores</h1>
            <?php foreach ($directors as $director) : ?>
                <li>
                    <?php if (isset($director->Nombre)) : ?>
                        <strong>Nombre:</strong> <?php echo $director->Nombre; ?><br>
                    <?php endif; ?>
                    <?php if (isset($director->Apellido)) : ?>
                        <strong>Apellido:</strong> <?php echo $director->Apellido; ?><br>
                    <?php endif; ?>
                    <?php if (isset($director->Nacionalidad)) : ?>
                        <strong>Nacionalidad:</strong> <?php echo $director->Nacionalidad; ?><br>
                    <?php endif; ?>
                    <?php if (!empty($director->peliculas)) : ?>
                        <p>Películas:</p>
                        <ul>
                            <?php foreach ($director->peliculas as $pelicula) : ?>
                                <li><?php echo $pelicula->nombre; ?></li>
                            <?php endforeach; ?>
                        </ul>
                        <br>
                    <?php else : ?>
                        <p>No se encontraron películas para este director.</p>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php else : ?>
        <p>No se encontraron películas que coincidan con la búsqueda.</p>
    <?php endif; ?>
</body>

</html>