<header>
    <nav>
        <div class="logo">
            <a href="home"><h1>MovieHunter</h1></a>
        </div>
        <div class="nav-links">
            <a href="directores">Directores</a>
            <a href="home">Inicio</a>
            <form action="buscarNombre" method="get">
                <input type="search" id="busqueda" name="name" required>
                <input type="submit" value="Buscar">
            </form>
        </div>
    </nav>
</header>