<!DOCTYPE html>
<html>
<head>
    <title>MovieHunter</title>
    <link rel="stylesheet" href="./styles/style.css">
</head>
<body>
    <?php require_once "header.phtml" ?>
    <main>
        <section class="hero">
            <h2>Las mejores películas en MovieHunter</h2>
            <p>¡Descubre una amplia selección de películas y series!</p>
            <div id="form-genres">
                <form action="buscar" method="get">
                    <div>
                        <input type="checkbox" name="Terror"> 
                        <h4>Terror</h4>
                    </div>
                    <div>
                        <input type="checkbox" name="Thriller"> 
                        <h4>Thriller</h4>
                    </div>
                    <div>
                        <input type="checkbox" name="Crimen"> 
                        <h4>Crimen</h4>
                    </div>
                    <div>
                        <input type="checkbox" name="Gore"> 
                        <h4>Gore</h4>
                    </div>
                    <div>
                        <input type="submit" value="Filtrar">
                    </div>
                </form>
            </div>
        </section>

        <section class="movies">
            <?php foreach ($movies as $movie) : ?>
                <a href="movie?id=<?php echo $movie->{'pelicula_id'}; ?>">
                    <div class="movie">
                        <img src="movie1.jpg" alt="Foto Película">
                        <h3><?php echo $movie->{'nombre'}?></h3>
                    </div>
                </a>
            <?php endforeach; ?>
        </section>
    </main>
    <?php require_once "Footer.phtml" ?>
</body>
</html>