<!DOCTYPE html>
<html>

<head>
    <title>MovieHunter</title>
    <link rel="stylesheet" href="./styles/style.css">
</head>

<body>



    <?php require 'templates/Header.phtml' ?>

    <div class="loginForm">
        <form method="POST" action="auth">
            <div class="form-group">
                <label for="username">Usuario</label>
                <input type="text" required class="form-control" id="username" name="username" aria-describedby="usernameHelp">
            </div>
            <div class="form-group">
                <label for="password">Contraseña</label>
                <input type="password" required class="form-control" id="password" name="password">
            </div>

            <?php if ($error) : ?>
                <div class="error">
                    <?= $error ?>
                </div>
            <?php endif ?>

            <button type="submit" class="btn btn-primary mt-3">Entrar</button>
        </form>
    </div>

    <?php require 'templates/Footer.phtml' ?>
</body>

</html>