<!DOCTYPE html>
<html>

<head>
    <title>Resultados de la búsqueda de películas</title>
    <link rel="stylesheet" href="./styles/style.css">
</head>

<body>
    <?php require_once "Header.phtml" ?>
    <main>
        <section class="category">
            <h2>Categoría 1</h2>
            <div class="movies">
                <?php foreach($movies as $movie):?>
                    <div class="movie">
                        <img src="category1_movie1.jpg" alt="Película">
                        <h3> <?php echo $movie->{'nombre'}?> </h3>
                    </div>
                <?php endforeach; ?>
            </div>
        </section>
    </main>
    <?php require_once "Footer.phtml" ?>
</body>
</html>