<!DOCTYPE html>
<html>

<head>
    <title>Buscar peliculas</title>
</head>

<body>
    <div>
        <form action="buscar" method="get">
            <label for="busqueda">Búsqueda:</label>
            <input type="text" id="busqueda" name="genero" placeholder="Género">
            <input type="submit" value="Buscar">
        </form>

        <p>
            <a href="/tpo">Go back home.</a>
        </p>

    </div>
</body>

</html>